services:
  postgres:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=postgrespw
    ports:
     - 5432:5432
    volumes:
     - pgdata:/var/lib/postresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO-INITDB_ROOT_USERNAME=root
      - MONG-INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
     - mongodata:/var/lib/mongodb/data
volumes: 
  pgdata:
  mongodata:
        